
/control/verbose 2
/run/verbose 2
#/tracking/verbose 2
#
/testhadr/phys/thermalScattering false
/testhadr/det/setMat polyethylene 
/testhadr/det/setSize 20 cm
#
/run/initialize
#
/gun/particle neutron
/gun/energy 2 MeV
#
/control/execute vis.mac
#
#
/score/create/boxMesh meshE_r
/score/mesh/boxSize 0.1 50 50 cm
/score/mesh/translate/xyz 45 0 0 cm
/score/mesh/nBin 50 50 50
/score/quantity/passageCellCurrent re0
/score/filter/particleWithKineticEnergy rr0 0 500 eV neutron
/score/quantity/passageCellCurrent re1
/score/filter/particleWithKineticEnergy rr1 0.5 1 keV neutron
/score/quantity/passageCellCurrent re2
/score/filter/particleWithKineticEnergy rr2 1 500 keV neutron
/score/quantity/passageCellCurrent re3
/score/filter/particleWithKineticEnergy rr3 0.5 1 MeV neutron
/score/quantity/passageCellCurrent re4
/score/filter/particleWithKineticEnergy rr4 1 2 MeV neutron
/score/quantity/passageCellCurrent reT
/score/filter/particle rrT neutron
/score/close
#
/score/create/boxMesh meshE_f
/score/mesh/boxSize 0.1 50 50 cm
/score/mesh/translate/xyz -45 0 0 cm
/score/mesh/nBin 50 50 50
/score/quantity/passageCellCurrent fe0
/score/filter/particleWithKineticEnergy fr0 0 500 eV neutron
/score/quantity/passageCellCurrent fe1
/score/filter/particleWithKineticEnergy fr1 0.5 1 keV neutron
/score/quantity/passageCellCurrent fe2
/score/filter/particleWithKineticEnergy fr2 1 500 keV neutron
/score/quantity/passageCellCurrent fe3
/score/filter/particleWithKineticEnergy fr3 0.5 1 MeV neutron
/score/quantity/passageCellCurrent fe4
/score/filter/particleWithKineticEnergy fr4 1 2 MeV neutron
/score/quantity/passageCellCurrent feT
/score/filter/particle frT neutron
/score/close
#
/score/colorMap/setMinMax defaultLinearColorMap 0 500
#
#/run/beamOn 10000
#